name: ubuntu

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install some package
      run: ./test emacs

    - name: Test installed package
      run: brew test emacs
